<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit27cce3cc84503932e5616d234e3dde12
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit27cce3cc84503932e5616d234e3dde12::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit27cce3cc84503932e5616d234e3dde12::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit27cce3cc84503932e5616d234e3dde12::$classMap;

        }, null, ClassLoader::class);
    }
}
